-- ======================================================
-- TABLE: Person
-- ======================================================
-- The Person table represents individual resources within the engineering organization.
-- Each record defines a unique person and captures employment type (FTE, Contractor),
-- active status, and general working location (e.g., Onshore, Offshore).
--
-- This table forms the human resource base of the capacity model.
-- It connects directly to:
--   Allocation: defines how a person's time is planned across workstreams.
--   Actual: records actual hours or effort logged by each person.
--   Scenario: identifies the user who created or owns a specific planning scenario.
--
-- Persons represent the real-world supply side of capacity planning.
-- Their aggregate availability, filtered by role and utilization target,
-- is used to calculate total organizational capacity by role and period.
CREATE TABLE Person (
    PersonID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    Name NVARCHAR(200) NOT NULL,
    EmploymentType NVARCHAR(50) NULL, -- FTE, Contractor, etc.
    IsActive bit,
    Location NVARCHAR(100) NULL, --onshore or offshore
    Constraint PK_Person Primary Key (PersonID)
)
INSERT INTO Person (Name, EmploymentType, IsActive, Location)
VALUES
('Abdul Mosin', 'FTE', 1, 'India'),
('Abhinava Mandikal', 'FTE', 1, 'India'),
('Aishwarya Rajaboina', 'FTE', 1, 'India'),
('Akshith Rachamalla', 'FTE', 1, 'India'),
('Amrutha Vadrevu', 'FTE', 1, 'India'),
('Anil Vidya Sagar Saila', 'FTE', 1, 'India'),
('Apoorba Ganguly', 'FTE', 1, 'India'),
('Ashok Palipi', 'FTE', 1, 'India'),
('Azhar Shaik', 'FTE', 1, 'India'),
('Bala Krishna Vijay Kumar Dwara', 'FTE', 1, 'India'),
('Bala Venkata Dunaboina', 'FTE', 1, 'India'),
('Bhavani Bandaru', 'FTE', 1, 'India'),
('Bimal Kurichiyath', 'FTE', 1, 'India'),
('Chinmayee Achary', 'FTE', 1, 'India'),
('Dilip Bikki', 'FTE', 1, 'India'),
('Durga Jyothi Ketha', 'FTE', 1, 'India'),
('Gaurav Kumar', 'FTE', 1, 'India'),
('Gayatri Chunduru', 'FTE', 1, 'India'),
('Gowtham Chowdary Meda', 'FTE', 1, 'India'),
('Gowthami Kilaru', 'FTE', 1, 'India'),
('Haritha Thoppe', 'FTE', 1, 'India'),
('Himabindu K', 'FTE', 1, 'India'),
('Himabindu T', 'FTE', 1, 'India'),
('Jeevan Kumar Poreddy', 'FTE', 1, 'India'),
('Kalyan Kilaru', 'FTE', 1, 'India'),
('Kalyan Prasad Kancharla', 'FTE', 1, 'India'),
('Karthik Garapati', 'FTE', 1, 'India'),
('Kiran Kumar', 'FTE', 1, 'India'),
('Krishna Teja', 'FTE', 1, 'India'),
('Lavanya Potluri', 'FTE', 1, 'India'),
('Madhuri Godavarthi', 'FTE', 1, 'India'),
('Manisha Chadalavada', 'FTE', 1, 'India'),
('Manoj Kumar', 'FTE', 1, 'India'),
('Manojkumar Golla', 'FTE', 1, 'India'),
('Manvitha Sanikommu', 'FTE', 1, 'India'),
('Mounika Gudapati', 'FTE', 1, 'India'),
('Mounika Patlolla', 'FTE', 1, 'India'),
('Nagamani Pidugu', 'FTE', 1, 'India'),
('Nagaraju Adabala', 'FTE', 1, 'India'),
('Nagendranadh J', 'FTE', 1, 'India'),
('Nagesh P', 'FTE', 1, 'India'),
('Naresh Kumar', 'FTE', 1, 'India'),
('Neelima Bathula', 'FTE', 1, 'India'),
('Niharika Mandadapu', 'FTE', 1, 'India'),
('Niharika Nagisetti', 'FTE', 1, 'India'),
('Nikitha P', 'FTE', 1, 'India'),
('Nikhil Reddy', 'FTE', 1, 'India'),
('Padmaja P', 'FTE', 1, 'India'),
('Pavan Kumar', 'FTE', 1, 'India'),
('Pooja Allu', 'FTE', 1, 'India'),
('Pooja Raj', 'FTE', 1, 'India'),
('Poonam Akula', 'FTE', 1, 'India'),
('Pradeep Danda', 'FTE', 1, 'India'),
('Pranitha Gundu', 'FTE', 1, 'India'),
('Prasanna Kalyani', 'FTE', 1, 'India'),
('Prathyusha P', 'FTE', 1, 'India'),
('Praveen Kumar', 'FTE', 1, 'India'),
('Priyanka D', 'FTE', 1, 'India'),
('Raj Kumar', 'FTE', 1, 'India'),
('Rajasekhar Chinnabathini', 'FTE', 1, 'India'),
('Rajesh Yadav', 'FTE', 1, 'India'),
('Rakesh Ch', 'FTE', 1, 'India'),
('Ramesh G', 'FTE', 1, 'India'),
('Ramu B', 'FTE', 1, 'India'),
('Ranga Reddy', 'FTE', 1, 'India'),
('Ravi Kottapalli', 'FTE', 1, 'India'),
('Ravi Teja', 'FTE', 1, 'India'),
('Rekha Yarramsetti', 'FTE', 1, 'India'),
('Rohith Reddy', 'FTE', 1, 'India'),
('Sai Kumar', 'FTE', 1, 'India'),
('Sai Teja', 'FTE', 1, 'India'),
('Sairam R', 'FTE', 1, 'India'),
('Sandhya B', 'FTE', 1, 'India'),
('Sandeep Reddy', 'FTE', 1, 'India'),
('Sangeetha B', 'FTE', 1, 'India'),
('Santhosh K', 'FTE', 1, 'India'),
('Satish Ch', 'FTE', 1, 'India'),
('Satya Prasad', 'FTE', 1, 'India'),
('Satyavathi P', 'FTE', 1, 'India'),
('Seetha Lakshmi', 'FTE', 1, 'India'),
('Shiva Kiran', 'FTE', 1, 'India'),
('Shravan Kumar', 'FTE', 1, 'India'),
('Siva Krishna', 'FTE', 1, 'India'),
('Sowmya Ch', 'FTE', 1, 'India'),
('Sravani D', 'FTE', 1, 'India'),
('Sreeja Mandadapu', 'FTE', 1, 'India'),
('Srilatha K', 'FTE', 1, 'India'),
('Sruthi K', 'FTE', 1, 'India'),
('Subhasish Pradhan', 'FTE', 1, 'India'),
('Sujatha K', 'FTE', 1, 'India'),
('Suresh P', 'FTE', 1, 'India'),
('Surya Prakash', 'FTE', 1, 'India'),
('Swathi K', 'FTE', 1, 'India'),
('Swetha B', 'FTE', 1, 'India'),
('Teja Reddy', 'FTE', 1, 'India'),
('Thirumal Reddy', 'FTE', 1, 'India'),
('Vamsi Krishna', 'FTE', 1, 'India'),
('Vasantha Kumar', 'FTE', 1, 'India'),
('Veerabhadra Rao', 'FTE', 1, 'India'),
('Venkat Reddy', 'FTE', 1, 'India'),
('Venkata Satish', 'FTE', 1, 'India'),
('Vinay Kumar', 'FTE', 1, 'India'),
('Vivek', 'FTE', 1, 'India'),
('Yeshwanth Reddy', 'FTE', 1, 'India')
